std::make_tuple(PixmapResourceId::ContactListSendingMark,			"cl",				"sending_mark"),
std::make_tuple(PixmapResourceId::ContactListReadMark,				"cl",				"read_mark"),
std::make_tuple(PixmapResourceId::ContactListDeliveredMark,			"cl",				"delivered_mark"),
std::make_tuple(PixmapResourceId::ContactListAddContact,			"cl",				"add_contact"),
std::make_tuple(PixmapResourceId::ContactListAddContactHovered,		"cl",				"add_contact_hover"),
std::make_tuple(PixmapResourceId::ContentMuteNotify,				"cl",				"mutenotify"),
std::make_tuple(PixmapResourceId::ContentMuteNotifyNew,				"cl",				"mutenotify_new"),

std::make_tuple(PixmapResourceId::FileSharingDownload,				"file_sharing",		"download"),
std::make_tuple(PixmapResourceId::FileSharingPlainCancel,			"file_sharing",		"plain_cancel"),
std::make_tuple(PixmapResourceId::FileSharingFileTypeIconUnknown,	"file_sharing",		"file_type_unknown"),

std::make_tuple(PixmapResourceId::PreviewerClose,					"previewer",		"close"),

std::make_tuple(PixmapResourceId::VoipEventMissedIcon,				"voip_events",		"missed_icon"),
std::make_tuple(PixmapResourceId::VoipEventIncomingCallIcon,		"voip_events",		"incoming_icon"),
std::make_tuple(PixmapResourceId::VoipEventOutgoingCallIcon,		"voip_events",		"outgoing_icon"),
std::make_tuple(PixmapResourceId::VoipEventCallEndedIcon,			"voip_events",		"call_ended_icon"),

std::make_tuple(PixmapResourceId::StickerHistoryPlaceholder,		"stickers",			"placeholder_history"),
std::make_tuple(PixmapResourceId::StickerPickerPlaceholder,			"stickers",			"placeholder_picker"),