#pragma once

#define auth_file_name "value.au"
#define auth_export_file_name "exported.json"
#define auth_export_file_name_merge "exportedmerge.json"
#define muted_chats_export_file_name "mutedchats.json"
#define settings_export_file_name "exported_ui.json"
#define core_settings_export_file_name "exported_core.json"
#define fetch_url_file_name "fetch"
#define gui_settings_file_name "ui2.stg"
#define hosts_config_file_name "hosts.stg"

#define settings_language "language"
#define settings_upload_directory "upload_directory"
#define settings_download_directory "download_directory"
#define settings_recents_stickers "recents_stickers"
#define settings_recents_emojis "recents_emojis"
#define settings_window_maximized "window_maximized"
#define settings_cl_groups_enabled "cl_groups_enabled"
#define settings_main_window_rect "main_window_rect"
#define settings_favorites_visible "favorites_visible"

#define settings_startup_at_system_started "startup_at_system_started"
#define settings_start_minimazed "start_minimazed"
#define settings_show_in_taskbar "show_in_taskbar"
#define settings_show_in_menubar "show_in_menubar"
#define settings_sounds_enabled "sounds_enabled"
#define settings_outgoing_message_sound_enabled "outgoing_message_sound_enabled"
#define settings_download_files_automatically "download_files_automatically"
#define settings_key1_to_send_message "key1_to_send_message"
#define settings_key2_to_send_message "key2_to_send_message"
#define settings_show_last_message "settings_show_last_message"
#define settings_show_video_and_images "show_video_and_images"
#define settings_autoplay_video "autoplay_video"
#define settings_auto_scroll_new_messages "auto_scroll_new_messages"
#define settings_scale_coefficient "scale_coefficient"
#define settings_sidebar_hide "hide_sidebar"
#define settings_show_snaps "settings_show_snaps"

#define settings_microphone "microphone"
#define settings_microphone_gain "microphone_gain"
#define settings_speakers "speakers"
#define settings_webcam "webcam"

#define settings_notify_new_messages "notify_new_messages"
#define settings_notify_new_mail_messages "notify_new_mail_messages"
#define settings_notify_birthdays "notify_birthdays"
#define settings_notify_contact_appearance "notify_contact_appearance"

#define settings_keep_logged_in "keep_logged_in"

#define settings_feedback_email "feedback_email"

#define settings_mac_accounts_migrated "mac_accounts_migrated"
#define settings_need_show_promo "need_show_promo"

#define settings_proxy_type "proxy_settings_type"
#define settings_proxy_address "proxy_settings_address"
#define settings_proxy_port "proxy_settings_port"
#define settings_proxy_username "proxy_settings_username"
#define settings_proxy_password "proxy_settings_password"

#define login_page_last_entered_uin "login_page_last_entered_uin"
#define login_page_last_entered_country_code "login_page_last_entered_country_code"
#define login_page_last_entered_phone "login_page_last_entered_phone"

#define setting_mplayer_volume "mplayer_volume"
#define setting_mplayer_mute "mplayer_mute"

#define product_path_icq_w L"ICQ"
#define product_path_icq_a "ICQ"
#define product_path_agent_w L"Mail.Ru/Agent"
#define product_path_agent_a "Mail.Ru/Agent"
#define product_path_agent_mac_w L"Mail.Ru Agent"
#define product_path_agent_mac_a "Mail.Ru Agent"
#define product_name_icq_mac_a "ICQ"
#define product_name_agent_mac_a "Mail.Ru Agent"

